// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag at
// 2018-02-17 21:44:06.959968 +0800 CST m=+0.051626564

package docs

import (
	"github.com/swaggo/swag"
)

var doc = `{
    "swagger": "2.0",
    "info": {
        "description": "dfsgdfsgfd",
        "title": "API",
        "termsOfService": "asfsadf",
        "contact": {
            "name": "API Support",
            "url": "dsgdfsg",
            "email": "fdssgfdsfd"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "1.0"
    },
    "host": "localhost",
    "basePath": "/v1",
    "paths": {
        "/v1/tags": {
            "get": {
                "description": "dfsgdfsgfd",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "fdsgfdsgfd",
                "operationId": "get-all-tags",
                "parameters": [
                    {
                        "type": "int",
                        "description": "Some ID",
                        "name": "some_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Tag"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "models.Tag": {
            "type": "object",
            "properties": {
                "ID": {
                    "type": "string"
                },
                "LabelType": {
                    "type": "LabelType"
                },
                "Name": {
                    "type": "string"
                },
                "Template": {
                    "type": "TagTemplate"
                }
            }
        }
    }
}`

type s struct{}

func (s *s) ReadDoc() string {
	return doc
}
func init() {
	swag.Register(swag.Name, &s{})
}
